import sys

from PPM_compressor import PPM_compressor
from PPM_decompressor import PPM_decompressor

# sys.stdout = open("debug_decompress_info.txt", "w")

if __name__ == "__main__":
    print('“' < (chr(257) + "ESC" + chr(257)))
    data = "Run-length Encoding is a simple yet effective form of lossless data compression. The basic idea behind RLE is to represent consecutive identical elements, called a “run” in a data stream by a single value and its count rather than as the original run. This is particularly useful when dealing with repetitive sequences, as it significantly reduces the amount of space needed to store or transmit the data."
    data = """Huffman encoding is a method of compressing strings. The key idea is to replace each character in the string by a sequence of bits in such a way that characters occurring more frequently have a shorter bit representation than characters occurring less frequently. This usually saves space compared to an encoding where all characters are represented by bit sequences of equal length (as, for example, in the standard ASCII encoding). For this, we have to compute the frequencies of all characters and then to organise that information in a binary tree. The tree can then be used for both the encoding and the decoding of the input string. See Wikipedia for a detailed description.

We are going to derive a (simplistic) Maple implementation of the functions needed to encode and to decode strings using Huffman's method. It will provide an example of how custom data structures (in this case binary trees) can be represented and used in Maple.The next step is to turn the frequency sequence into a Huffman tree. Although it is possible to represent trees in Maple by simply using nested lists, we will implement a more advanced method. This will be both more readable and less error-prone. The idea is to introduce data types for nodes and leaves of our trees. We will use an expression of the form Leaf(d) to represent a leaf with data d and we will use Node(l,r) for representing a node with left subtree l and right subtree r.

Maple does not have a formal data type declaration and in fact, we could use the expressions just without further preparations. However, we decide to enable type checking for our trees. This way, we can later easily check whether something is a leaf or node. Also, we can use the types in the argument lists of procedures in order to guard ourselves against wrong input."""
    # data = "Run-length Encoding is a simple yet effective form of lossless data compression. The basic idea behind RLE is to represent consecutive identical elements, called a “run”"
    ppm_compressor = PPM_compressor(4)
    encoded_data = ppm_compressor.encode_data(data)

    ppm_decompressor = PPM_decompressor(4)
    orig_data = ppm_decompressor.decode_data(encoded_data, ppm_compressor.get_diffrent_symbols_cnt(data)[1], len(data))
    print(data)
    print(orig_data)
    print(orig_data == data)

    # for i in range(len(data)):
    #     if data[i] != orig_data[i]:
    #         print(data[i], orig_data[i])

    a = {-1: {'R': 1, 'u': 1, 'n': 1, '-': 1, 'l': 1, 'e': 1, 'g': 1, 't': 1, 'h': 1, ' ': 1, 'E': 1, 'c': 1, 'o': 1,
              'd': 1, 'i': 1, 's': 1, 'a': 1, 'm': 1, 'p': 1, 'y': 1, 'f': 1, 'v': 1, 'r': 1, '.': 1, 'T': 1, 'b': 1,
              'L': 1, ',': 1, '“': 1, '”': 1, 'w': 1, 'q': 1},
         '': {'R': 2, 'āESCā': 29, 'u': 3, 'n': 11, '-': 1, 'l': 8, 'e': 21, 'g': 2, 't': 9, 'h': 3, ' ': 25, 'E': 2,
              'c': 8, 'o': 8, 'd': 6, 'i': 12, 's': 13, 'a': 8, 'm': 4, 'p': 3, 'y': 1, 'f': 4, 'v': 2, 'r': 5, '.': 1,
              'T': 1, 'b': 2, 'L': 1, ',': 1, '“': 1}, 'R': {'u': 1, 'āESCā': 2, 'L': 1}, 'Ru': {'n': 1, 'āESCā': 1},
         'u': {'n': 2, 'āESCā': 2, 't': 1}, 'Run': {'-': 1, 'āESCā': 1}, 'un': {'-': 1, 'āESCā': 1},
         'n': {'-': 1, 'āESCā': 7, 'g': 2, 'c': 1, '.': 1, 'd': 1, 't': 3, 's': 1}, 'Run-': {'l': 1, 'āESCā': 1},
         'un-': {'l': 1, 'āESCā': 1}, 'n-': {'l': 1, 'āESCā': 1}, '-': {'l': 1, 'āESCā': 1},
         'un-l': {'e': 1, 'āESCā': 1},
         'n-l': {'e': 1, 'āESCā': 1}, '-l': {'e': 1, 'āESCā': 1}, 'l': {'e': 5, 'āESCā': 4, 'o': 1, ' ': 1, 'l': 1},
         'n-le': {'n': 1, 'āESCā': 1}, '-le': {'n': 1, 'āESCā': 1},
         'le': {'n': 1, 'āESCā': 5, ' ': 1, 's': 1, 'm': 1, 'd': 1},
         'e': {'n': 4, 'āESCā': 12, ' ': 4, 't': 1, 'f': 1, 'c': 2, 's': 3, 'a': 1, 'h': 1, 'p': 1, 'l': 1, 'm': 1,
               'd': 1},
         '-len': {'g': 1, 'āESCā': 1}, 'len': {'g': 1, 'āESCā': 1}, 'en': {'g': 1, 'āESCā': 2, 't': 3},
         'leng': {'t': 1, 'āESCā': 1}, 'eng': {'t': 1, 'āESCā': 1}, 'ng': {'t': 1, 'āESCā': 2, ' ': 1},
         'g': {'t': 1, 'āESCā': 2, ' ': 1}, 'engt': {'h': 1, 'āESCā': 1}, 'ngt': {'h': 1, 'āESCā': 1},
         'gt': {'h': 1, 'āESCā': 1}, 't': {'h': 1, 'āESCā': 6, ' ': 2, 'i': 3, 'a': 1, 'o': 1, 's': 1},
         'ngth': {' ': 1, 'āESCā': 1}, 'gth': {' ': 1, 'āESCā': 1}, 'th': {' ': 1, 'āESCā': 1},
         'h': {' ': 1, 'āESCā': 3, 'e': 1, 'i': 1}, 'gth ': {'E': 1, 'āESCā': 1}, 'th ': {'E': 1, 'āESCā': 1},
         'h ': {'E': 1, 'āESCā': 1},
         ' ': {'E': 1, 'āESCā': 17, 'i': 4, 'a': 2, 's': 1, 'y': 1, 'e': 2, 'f': 1, 'o': 1, 'l': 1, 'd': 1, 'c': 3,
               'T': 1,
               'b': 2, 'R': 1, 't': 1, 'r': 1, '“': 1}, 'th E': {'n': 1, 'āESCā': 1}, 'h E': {'n': 1, 'āESCā': 1},
         ' E': {'n': 1, 'āESCā': 1}, 'E': {'n': 1, 'āESCā': 2, ' ': 1}, 'h En': {'c': 1, 'āESCā': 1},
         ' En': {'c': 1, 'āESCā': 1}, 'En': {'c': 1, 'āESCā': 1}, ' Enc': {'o': 1, 'āESCā': 1},
         'Enc': {'o': 1, 'āESCā': 1},
         'nc': {'o': 1, 'āESCā': 1}, 'c': {'o': 3, 'āESCā': 5, 't': 1, ' ': 1, 'u': 1, 'a': 2},
         'Enco': {'d': 1, 'āESCā': 1}, 'nco': {'d': 1, 'āESCā': 1}, 'co': {'d': 1, 'āESCā': 3, 'm': 1, 'n': 1},
         'o': {'d': 1, 'āESCā': 7, 'r': 1, 'f': 1, 's': 1, 'm': 1, 'n': 2, ' ': 1}, 'ncod': {'i': 1, 'āESCā': 1},
         'cod': {'i': 1, 'āESCā': 1}, 'od': {'i': 1, 'āESCā': 1}, 'd': {'i': 1, 'āESCā': 4, 'a': 1, 'e': 2, ' ': 2},
         'codi': {'n': 1, 'āESCā': 1}, 'odi': {'n': 1, 'āESCā': 1}, 'di': {'n': 1, 'āESCā': 1},
         'i': {'n': 2, 'āESCā': 7, 's': 2, 'm': 1, 'v': 2, 'o': 1, 'c': 2, 'd': 2}, 'odin': {'g': 1, 'āESCā': 1},
         'din': {'g': 1, 'āESCā': 1}, 'in': {'g': 1, 'āESCā': 2, 'd': 1}, 'ding': {' ': 1, 'āESCā': 1},
         'ing': {' ': 1, 'āESCā': 1}, 'ing ': {'i': 1, 'āESCā': 1}, 'ng ': {'i': 1, 'āESCā': 1},
         'g ': {'i': 1, 'āESCā': 1},
         'ng i': {'s': 1, 'āESCā': 1}, 'g i': {'s': 1, 'āESCā': 1}, ' i': {'s': 2, 'āESCā': 2, 'd': 2},
         'g is': {' ': 1, 'āESCā': 1}, ' is': {' ': 2, 'āESCā': 1}, 'is': {' ': 2, 'āESCā': 1},
         's': {' ': 3, 'āESCā': 6, 'i': 3, 's': 3, 'l': 1, 'e': 2, ',': 1}, ' is ': {'a': 1, 'āESCā': 2, 't': 1},
         'is ': {'a': 1, 'āESCā': 2, 't': 1}, 's ': {'a': 1, 'āESCā': 3, 'd': 1, 't': 1}, 'is a': {' ': 1, 'āESCā': 1},
         's a': {' ': 1, 'āESCā': 1}, ' a': {' ': 2, 'āESCā': 1}, 'a': {' ': 4, 'āESCā': 4, 't': 1, 's': 1, 'l': 2},
         's a ': {'s': 1, 'āESCā': 1}, ' a ': {'s': 1, 'āESCā': 2, '“': 1},
         'a ': {'s': 1, 'āESCā': 4, 'c': 1, 'b': 1, '“': 1}, ' a s': {'i': 1, 'āESCā': 1}, 'a s': {'i': 1, 'āESCā': 1},
         ' s': {'i': 1, 'āESCā': 1}, 'a si': {'m': 1, 'āESCā': 1}, ' si': {'m': 1, 'āESCā': 1},
         'si': {'m': 1, 'āESCā': 3, 'o': 1, 'c': 1}, ' sim': {'p': 1, 'āESCā': 1}, 'sim': {'p': 1, 'āESCā': 1},
         'im': {'p': 1, 'āESCā': 1}, 'm': {'p': 2, 'āESCā': 3, ' ': 1, 'e': 1}, 'simp': {'l': 1, 'āESCā': 1},
         'imp': {'l': 1, 'āESCā': 1}, 'mp': {'l': 1, 'āESCā': 2, 'r': 1}, 'p': {'l': 1, 'āESCā': 2, 'r': 2},
         'impl': {'e': 1, 'āESCā': 1}, 'mpl': {'e': 1, 'āESCā': 1}, 'pl': {'e': 1, 'āESCā': 1},
         'mple': {' ': 1, 'āESCā': 1}, 'ple': {' ': 1, 'āESCā': 1}, 'ple ': {'y': 1, 'āESCā': 1},
         'le ': {'y': 1, 'āESCā': 1}, 'e ': {'y': 1, 'āESCā': 4, 'f': 1, 'b': 1, 'i': 1}, 'le y': {'e': 1, 'āESCā': 1},
         'e y': {'e': 1, 'āESCā': 1}, ' y': {'e': 1, 'āESCā': 1}, 'y': {'e': 1, 'āESCā': 1},
         'e ye': {'t': 1, 'āESCā': 1},
         ' ye': {'t': 1, 'āESCā': 1}, 'ye': {'t': 1, 'āESCā': 1}, ' yet': {' ': 1, 'āESCā': 1},
         'yet': {' ': 1, 'āESCā': 1},
         'et': {' ': 1, 'āESCā': 1}, 'yet ': {'e': 1, 'āESCā': 1}, 'et ': {'e': 1, 'āESCā': 1},
         't ': {'e': 1, 'āESCā': 2, 'c': 1}, 'et e': {'f': 1, 'āESCā': 1}, 't e': {'f': 1, 'āESCā': 1},
         ' e': {'f': 1, 'āESCā': 2, 'l': 1}, 't ef': {'f': 1, 'āESCā': 1}, ' ef': {'f': 1, 'āESCā': 1},
         'ef': {'f': 1, 'āESCā': 1}, 'f': {'f': 1, 'āESCā': 4, 'e': 1, 'o': 1, ' ': 1}, ' eff': {'e': 1, 'āESCā': 1},
         'eff': {'e': 1, 'āESCā': 1}, 'ff': {'e': 1, 'āESCā': 1}, 'effe': {'c': 1, 'āESCā': 1},
         'ffe': {'c': 1, 'āESCā': 1},
         'fe': {'c': 1, 'āESCā': 1}, 'ffec': {'t': 1, 'āESCā': 1}, 'fec': {'t': 1, 'āESCā': 1},
         'ec': {'t': 1, 'āESCā': 2, 'u': 1}, 'fect': {'i': 1, 'āESCā': 1}, 'ect': {'i': 1, 'āESCā': 1},
         'ct': {'i': 1, 'āESCā': 1}, 'ecti': {'v': 1, 'āESCā': 1}, 'cti': {'v': 1, 'āESCā': 1},
         'ti': {'v': 2, 'āESCā': 2, 'c': 1}, 'ctiv': {'e': 1, 'āESCā': 1}, 'tiv': {'e': 2, 'āESCā': 1},
         'iv': {'e': 2, 'āESCā': 1}, 'v': {'e': 2, 'āESCā': 1}, 'tive': {' ': 2, 'āESCā': 1},
         'ive': {' ': 2, 'āESCā': 1},
         've': {' ': 2, 'āESCā': 1}, 'ive ': {'f': 1, 'āESCā': 2, 'i': 1}, 've ': {'f': 1, 'āESCā': 2, 'i': 1},
         've f': {'o': 1, 'āESCā': 1}, 'e f': {'o': 1, 'āESCā': 1}, ' f': {'o': 1, 'āESCā': 1},
         'e fo': {'r': 1, 'āESCā': 1}, ' fo': {'r': 1, 'āESCā': 1}, 'fo': {'r': 1, 'āESCā': 1},
         ' for': {'m': 1, 'āESCā': 1}, 'for': {'m': 1, 'āESCā': 1}, 'or': {'m': 1, 'āESCā': 1},
         'r': {'m': 1, 'āESCā': 3, 'e': 3, 'u': 1}, 'form': {' ': 1, 'āESCā': 1}, 'orm': {' ': 1, 'āESCā': 1},
         'rm': {' ': 1, 'āESCā': 1}, 'orm ': {'o': 1, 'āESCā': 1}, 'rm ': {'o': 1, 'āESCā': 1},
         'm ': {'o': 1, 'āESCā': 1},
         'rm o': {'f': 1, 'āESCā': 1}, 'm o': {'f': 1, 'āESCā': 1}, ' o': {'f': 1, 'āESCā': 1},
         'm of': {' ': 1, 'āESCā': 1}, ' of': {' ': 1, 'āESCā': 1}, 'of': {' ': 1, 'āESCā': 1},
         ' of ': {'l': 1, 'āESCā': 1}, 'of ': {'l': 1, 'āESCā': 1}, 'f ': {'l': 1, 'āESCā': 1},
         'of l': {'o': 1, 'āESCā': 1}, 'f l': {'o': 1, 'āESCā': 1}, ' l': {'o': 1, 'āESCā': 1},
         'f lo': {'s': 1, 'āESCā': 1}, ' lo': {'s': 1, 'āESCā': 1}, 'lo': {'s': 1, 'āESCā': 1},
         ' los': {'s': 1, 'āESCā': 1}, 'los': {'s': 1, 'āESCā': 1}, 'os': {'s': 1, 'āESCā': 1},
         'loss': {'l': 1, 'āESCā': 1}, 'oss': {'l': 1, 'āESCā': 1}, 'ss': {'l': 1, 'āESCā': 3, ' ': 1, 'i': 1},
         'ossl': {'e': 1, 'āESCā': 1}, 'ssl': {'e': 1, 'āESCā': 1}, 'sl': {'e': 1, 'āESCā': 1},
         'ssle': {'s': 1, 'āESCā': 1}, 'sle': {'s': 1, 'āESCā': 1}, 'sles': {'s': 1, 'āESCā': 1},
         'les': {'s': 1, 'āESCā': 1}, 'es': {'s': 2, 'āESCā': 2, 'e': 1}, 'less': {' ': 1, 'āESCā': 1},
         'ess': {' ': 1, 'āESCā': 2, 'i': 1}, 'ess ': {'d': 1, 'āESCā': 1}, 'ss ': {'d': 1, 'āESCā': 1},
         'ss d': {'a': 1, 'āESCā': 1}, 's d': {'a': 1, 'āESCā': 1}, ' d': {'a': 1, 'āESCā': 1},
         's da': {'t': 1, 'āESCā': 1}, ' da': {'t': 1, 'āESCā': 1}, 'da': {'t': 1, 'āESCā': 1},
         ' dat': {'a': 1, 'āESCā': 1}, 'dat': {'a': 1, 'āESCā': 1}, 'at': {'a': 1, 'āESCā': 1},
         'data': {' ': 1, 'āESCā': 1}, 'ata': {' ': 1, 'āESCā': 1}, 'ta': {' ': 1, 'āESCā': 1},
         'ata ': {'c': 1, 'āESCā': 1}, 'ta ': {'c': 1, 'āESCā': 1}, 'ta c': {'o': 1, 'āESCā': 1},
         'a c': {'o': 1, 'āESCā': 1}, ' c': {'o': 2, 'āESCā': 2, 'a': 1}, 'a co': {'m': 1, 'āESCā': 1},
         ' co': {'m': 1, 'āESCā': 2, 'n': 1}, ' com': {'p': 1, 'āESCā': 1}, 'com': {'p': 1, 'āESCā': 1},
         'om': {'p': 1, 'āESCā': 1}, 'comp': {'r': 1, 'āESCā': 1}, 'omp': {'r': 1, 'āESCā': 1},
         'ompr': {'e': 1, 'āESCā': 1}, 'mpr': {'e': 1, 'āESCā': 1}, 'pr': {'e': 2, 'āESCā': 1},
         'mpre': {'s': 1, 'āESCā': 1}, 'pre': {'s': 2, 'āESCā': 1}, 're': {'s': 2, 'āESCā': 2, 'p': 1},
         'pres': {'s': 1, 'āESCā': 2, 'e': 1}, 'res': {'s': 1, 'āESCā': 2, 'e': 1}, 'ress': {'i': 1, 'āESCā': 1},
         'essi': {'o': 1, 'āESCā': 1}, 'ssi': {'o': 1, 'āESCā': 1}, 'ssio': {'n': 1, 'āESCā': 1},
         'sio': {'n': 1, 'āESCā': 1}, 'io': {'n': 1, 'āESCā': 1}, 'sion': {'.': 1, 'āESCā': 1},
         'ion': {'.': 1, 'āESCā': 1},
         'on': {'.': 1, 'āESCā': 2, 's': 1}, 'ion.': {' ': 1, 'āESCā': 1}, 'on.': {' ': 1, 'āESCā': 1},
         'n.': {' ': 1, 'āESCā': 1}, '.': {' ': 1, 'āESCā': 1}, 'on. ': {'T': 1, 'āESCā': 1},
         'n. ': {'T': 1, 'āESCā': 1},
         '. ': {'T': 1, 'āESCā': 1}, 'n. T': {'h': 1, 'āESCā': 1}, '. T': {'h': 1, 'āESCā': 1},
         ' T': {'h': 1, 'āESCā': 1},
         'T': {'h': 1, 'āESCā': 1}, '. Th': {'e': 1, 'āESCā': 1}, ' Th': {'e': 1, 'āESCā': 1},
         'Th': {'e': 1, 'āESCā': 1},
         ' The': {' ': 1, 'āESCā': 1}, 'The': {' ': 1, 'āESCā': 1}, 'he': {' ': 1, 'āESCā': 1},
         'The ': {'b': 1, 'āESCā': 1}, 'he ': {'b': 1, 'āESCā': 1}, 'he b': {'a': 1, 'āESCā': 1},
         'e b': {'a': 1, 'āESCā': 1}, ' b': {'a': 1, 'āESCā': 2, 'e': 1}, 'b': {'a': 1, 'āESCā': 2, 'e': 1},
         'e ba': {'s': 1, 'āESCā': 1}, ' ba': {'s': 1, 'āESCā': 1}, 'ba': {'s': 1, 'āESCā': 1},
         ' bas': {'i': 1, 'āESCā': 1}, 'bas': {'i': 1, 'āESCā': 1}, 'as': {'i': 1, 'āESCā': 1},
         'basi': {'c': 1, 'āESCā': 1}, 'asi': {'c': 1, 'āESCā': 1}, 'asic': {' ': 1, 'āESCā': 1},
         'sic': {' ': 1, 'āESCā': 1}, 'ic': {' ': 1, 'āESCā': 2, 'a': 1}, 'sic ': {'i': 1, 'āESCā': 1},
         'ic ': {'i': 1, 'āESCā': 1}, 'c ': {'i': 1, 'āESCā': 1}, 'ic i': {'d': 1, 'āESCā': 1},
         'c i': {'d': 1, 'āESCā': 1},
         'c id': {'e': 1, 'āESCā': 1}, ' id': {'e': 2, 'āESCā': 1}, 'id': {'e': 2, 'āESCā': 1},
         ' ide': {'a': 1, 'āESCā': 2, 'n': 1}, 'ide': {'a': 1, 'āESCā': 2, 'n': 1}, 'de': {'a': 1, 'āESCā': 2, 'n': 1},
         'idea': {' ': 1, 'āESCā': 1}, 'dea': {' ': 1, 'āESCā': 1}, 'ea': {' ': 1, 'āESCā': 1},
         'dea ': {'b': 1, 'āESCā': 1}, 'ea ': {'b': 1, 'āESCā': 1}, 'ea b': {'e': 1, 'āESCā': 1},
         'a b': {'e': 1, 'āESCā': 1}, 'a be': {'h': 1, 'āESCā': 1}, ' be': {'h': 1, 'āESCā': 1},
         'be': {'h': 1, 'āESCā': 1},
         ' beh': {'i': 1, 'āESCā': 1}, 'beh': {'i': 1, 'āESCā': 1}, 'eh': {'i': 1, 'āESCā': 1},
         'behi': {'n': 1, 'āESCā': 1}, 'ehi': {'n': 1, 'āESCā': 1}, 'hi': {'n': 1, 'āESCā': 1},
         'ehin': {'d': 1, 'āESCā': 1}, 'hin': {'d': 1, 'āESCā': 1}, 'hind': {' ': 1, 'āESCā': 1},
         'ind': {' ': 1, 'āESCā': 1}, 'nd': {' ': 1, 'āESCā': 1}, 'ind ': {'R': 1, 'āESCā': 1},
         'nd ': {'R': 1, 'āESCā': 1},
         'd ': {'R': 1, 'āESCā': 2, 'a': 1}, 'nd R': {'L': 1, 'āESCā': 1}, 'd R': {'L': 1, 'āESCā': 1},
         ' R': {'L': 1, 'āESCā': 1}, 'd RL': {'E': 1, 'āESCā': 1}, ' RL': {'E': 1, 'āESCā': 1},
         'RL': {'E': 1, 'āESCā': 1},
         'L': {'E': 1, 'āESCā': 1}, ' RLE': {' ': 1, 'āESCā': 1}, 'RLE': {' ': 1, 'āESCā': 1},
         'LE': {' ': 1, 'āESCā': 1},
         'RLE ': {'i': 1, 'āESCā': 1}, 'LE ': {'i': 1, 'āESCā': 1}, 'E ': {'i': 1, 'āESCā': 1},
         'LE i': {'s': 1, 'āESCā': 1}, 'E i': {'s': 1, 'āESCā': 1}, 'E is': {' ': 1, 'āESCā': 1},
         'is t': {'o': 1, 'āESCā': 1}, 's t': {'o': 1, 'āESCā': 1}, ' t': {'o': 1, 'āESCā': 1},
         's to': {' ': 1, 'āESCā': 1}, ' to': {' ': 1, 'āESCā': 1}, 'to': {' ': 1, 'āESCā': 1},
         ' to ': {'r': 1, 'āESCā': 1}, 'to ': {'r': 1, 'āESCā': 1}, 'o ': {'r': 1, 'āESCā': 1},
         'to r': {'e': 1, 'āESCā': 1}, 'o r': {'e': 1, 'āESCā': 1}, ' r': {'e': 1, 'āESCā': 1},
         'o re': {'p': 1, 'āESCā': 1}, ' re': {'p': 1, 'āESCā': 1}, ' rep': {'r': 1, 'āESCā': 1},
         'rep': {'r': 1, 'āESCā': 1}, 'ep': {'r': 1, 'āESCā': 1}, 'repr': {'e': 1, 'āESCā': 1},
         'epr': {'e': 1, 'āESCā': 1},
         'epre': {'s': 1, 'āESCā': 1}, 'rese': {'n': 1, 'āESCā': 1}, 'ese': {'n': 1, 'āESCā': 1},
         'se': {'n': 1, 'āESCā': 2, 'c': 1}, 'esen': {'t': 1, 'āESCā': 1}, 'sen': {'t': 1, 'āESCā': 1},
         'sent': {' ': 1, 'āESCā': 1}, 'ent': {' ': 1, 'āESCā': 3, 'i': 1, 's': 1},
         'nt': {' ': 1, 'āESCā': 3, 'i': 1, 's': 1}, 'ent ': {'c': 1, 'āESCā': 1}, 'nt ': {'c': 1, 'āESCā': 1},
         'nt c': {'o': 1, 'āESCā': 1}, 't c': {'o': 1, 'āESCā': 1}, 't co': {'n': 1, 'āESCā': 1},
         ' con': {'s': 1, 'āESCā': 1}, 'con': {'s': 1, 'āESCā': 1}, 'cons': {'e': 1, 'āESCā': 1},
         'ons': {'e': 1, 'āESCā': 1}, 'ns': {'e': 1, 'āESCā': 1}, 'onse': {'c': 1, 'āESCā': 1},
         'nse': {'c': 1, 'āESCā': 1},
         'nsec': {'u': 1, 'āESCā': 1}, 'sec': {'u': 1, 'āESCā': 1}, 'secu': {'t': 1, 'āESCā': 1},
         'ecu': {'t': 1, 'āESCā': 1}, 'cu': {'t': 1, 'āESCā': 1}, 'ecut': {'i': 1, 'āESCā': 1},
         'cut': {'i': 1, 'āESCā': 1},
         'ut': {'i': 1, 'āESCā': 1}, 'cuti': {'v': 1, 'āESCā': 1}, 'uti': {'v': 1, 'āESCā': 1},
         'utiv': {'e': 1, 'āESCā': 1}, 've i': {'d': 1, 'āESCā': 1}, 'e i': {'d': 1, 'āESCā': 1},
         'e id': {'e': 1, 'āESCā': 1}, 'iden': {'t': 1, 'āESCā': 1}, 'den': {'t': 1, 'āESCā': 1},
         'dent': {'i': 1, 'āESCā': 1}, 'enti': {'c': 1, 'āESCā': 1}, 'nti': {'c': 1, 'āESCā': 1},
         'ntic': {'a': 1, 'āESCā': 1}, 'tic': {'a': 1, 'āESCā': 1}, 'tica': {'l': 1, 'āESCā': 1},
         'ica': {'l': 1, 'āESCā': 1}, 'ca': {'l': 2, 'āESCā': 1}, 'ical': {' ': 1, 'āESCā': 1},
         'cal': {' ': 1, 'āESCā': 2, 'l': 1}, 'al': {' ': 1, 'āESCā': 2, 'l': 1}, 'cal ': {'e': 1, 'āESCā': 1},
         'al ': {'e': 1, 'āESCā': 1}, 'l ': {'e': 1, 'āESCā': 1}, 'al e': {'l': 1, 'āESCā': 1},
         'l e': {'l': 1, 'āESCā': 1},
         'l el': {'e': 1, 'āESCā': 1}, ' el': {'e': 1, 'āESCā': 1}, 'el': {'e': 1, 'āESCā': 1},
         ' ele': {'m': 1, 'āESCā': 1}, 'ele': {'m': 1, 'āESCā': 1}, 'elem': {'e': 1, 'āESCā': 1},
         'lem': {'e': 1, 'āESCā': 1}, 'em': {'e': 1, 'āESCā': 1}, 'leme': {'n': 1, 'āESCā': 1},
         'eme': {'n': 1, 'āESCā': 1},
         'me': {'n': 1, 'āESCā': 1}, 'emen': {'t': 1, 'āESCā': 1}, 'men': {'t': 1, 'āESCā': 1},
         'ment': {'s': 1, 'āESCā': 1}, 'ents': {',': 1, 'āESCā': 1}, 'nts': {',': 1, 'āESCā': 1},
         'ts': {',': 1, 'āESCā': 1}, 'nts,': {' ': 1, 'āESCā': 1}, 'ts,': {' ': 1, 'āESCā': 1},
         's,': {' ': 1, 'āESCā': 1},
         ',': {' ': 1, 'āESCā': 1}, 'ts, ': {'c': 1, 'āESCā': 1}, 's, ': {'c': 1, 'āESCā': 1},
         ', ': {'c': 1, 'āESCā': 1},
         's, c': {'a': 1, 'āESCā': 1}, ', c': {'a': 1, 'āESCā': 1}, ', ca': {'l': 1, 'āESCā': 1},
         ' ca': {'l': 1, 'āESCā': 1}, ' cal': {'l': 1, 'āESCā': 1}, 'call': {'e': 1, 'āESCā': 1},
         'all': {'e': 1, 'āESCā': 1}, 'll': {'e': 1, 'āESCā': 1}, 'alle': {'d': 1, 'āESCā': 1},
         'lle': {'d': 1, 'āESCā': 1},
         'lled': {' ': 1, 'āESCā': 1}, 'led': {' ': 1, 'āESCā': 1}, 'ed': {' ': 1, 'āESCā': 1},
         'led ': {'a': 1, 'āESCā': 1}, 'ed ': {'a': 1, 'āESCā': 1}, 'ed a': {' ': 1, 'āESCā': 1},
         'd a': {' ': 1, 'āESCā': 1}, 'd a ': {'“': 1, 'āESCā': 1}, ' a “': {'r': 1, 'āESCā': 1},
         'a “': {'r': 1, 'āESCā': 1}, ' “': {'r': 1, 'āESCā': 1}, '“': {'r': 1, 'āESCā': 1},
         'a “r': {'u': 1, 'āESCā': 1},
         ' “r': {'u': 1, 'āESCā': 1}, '“r': {'u': 1, 'āESCā': 1}, ' “ru': {'n': 1, 'āESCā': 1},
         '“ru': {'n': 1, 'āESCā': 1},
         'ru': {'n': 1, 'āESCā': 1}}

    b = {-1: {'R': 1, 'u': 1, 'n': 1, '-': 1, 'l': 1, 'e': 1, 'g': 1, 't': 1, 'h': 1, ' ': 1, 'E': 1, 'c': 1, 'o': 1,
              'd': 1, 'i': 1, 's': 1, 'a': 1, 'm': 1, 'p': 1, 'y': 1, 'f': 1, 'v': 1, 'r': 1, '.': 1, 'T': 1, 'b': 1,
              'L': 1, ',': 1, '“': 1, '”': 1, 'w': 1, 'q': 1},
         '': {'R': 2, 'āESCā': 29, 'u': 3, 'n': 11, '-': 1, 'l': 8, 'e': 21, 'g': 2, 't': 9, 'h': 3, ' ': 25, 'E': 2,
              'c': 8, 'o': 8, 'd': 6, 'i': 12, 's': 13, 'a': 8, 'm': 4, 'p': 3, 'y': 1, 'f': 4, 'v': 2, 'r': 5, '.': 1,
              'T': 1, 'b': 2, 'L': 1, ',': 1, '“': 1}, 'R': {'u': 1, 'āESCā': 2, 'L': 1}, 'Ru': {'n': 1, 'āESCā': 1},
         'u': {'n': 2, 'āESCā': 2, 't': 1}, 'Run': {'-': 1, 'āESCā': 1}, 'un': {'-': 1, 'āESCā': 1},
         'n': {'-': 1, 'āESCā': 7, 'g': 2, 'c': 1, '.': 1, 'd': 1, 't': 3, 's': 1}, 'Run-': {'l': 1, 'āESCā': 1},
         'un-': {'l': 1, 'āESCā': 1}, 'n-': {'l': 1, 'āESCā': 1}, '-': {'l': 1, 'āESCā': 1},
         'un-l': {'e': 1, 'āESCā': 1}, 'n-l': {'e': 1, 'āESCā': 1}, '-l': {'e': 1, 'āESCā': 1},
         'l': {'e': 5, 'āESCā': 4, 'o': 1, ' ': 1, 'l': 1}, 'n-le': {'n': 1, 'āESCā': 1}, '-le': {'n': 1, 'āESCā': 1},
         'le': {'n': 1, 'āESCā': 5, ' ': 1, 's': 1, 'm': 1, 'd': 1},
         'e': {'n': 4, 'āESCā': 12, ' ': 4, 't': 1, 'f': 1, 'c': 2, 's': 3, 'a': 1, 'h': 1, 'p': 1, 'l': 1, 'm': 1,
               'd': 1}, '-len': {'g': 1, 'āESCā': 1}, 'len': {'g': 1, 'āESCā': 1}, 'en': {'g': 1, 'āESCā': 2, 't': 3},
         'leng': {'t': 1, 'āESCā': 1}, 'eng': {'t': 1, 'āESCā': 1}, 'ng': {'t': 1, 'āESCā': 2, ' ': 1},
         'g': {'t': 1, 'āESCā': 2, ' ': 1}, 'engt': {'h': 1, 'āESCā': 1}, 'ngt': {'h': 1, 'āESCā': 1},
         'gt': {'h': 1, 'āESCā': 1}, 't': {'h': 1, 'āESCā': 6, ' ': 2, 'i': 3, 'a': 1, 'o': 1, 's': 1},
         'ngth': {' ': 1, 'āESCā': 1}, 'gth': {' ': 1, 'āESCā': 1}, 'th': {' ': 1, 'āESCā': 1},
         'h': {' ': 1, 'āESCā': 3, 'e': 1, 'i': 1}, 'gth ': {'E': 1, 'āESCā': 1}, 'th ': {'E': 1, 'āESCā': 1},
         'h ': {'E': 1, 'āESCā': 1},
         ' ': {'E': 1, 'āESCā': 17, 'i': 4, 'a': 2, 's': 1, 'y': 1, 'e': 2, 'f': 1, 'o': 1, 'l': 1, 'd': 1, 'c': 3,
               'T': 1, 'b': 2, 'R': 1, 't': 1, 'r': 1, '“': 1}, 'th E': {'n': 1, 'āESCā': 1},
         'h E': {'n': 1, 'āESCā': 1}, ' E': {'n': 1, 'āESCā': 1}, 'E': {'n': 1, 'āESCā': 2, ' ': 1},
         'h En': {'c': 1, 'āESCā': 1}, ' En': {'c': 1, 'āESCā': 1}, 'En': {'c': 1, 'āESCā': 1},
         ' Enc': {'o': 1, 'āESCā': 1}, 'Enc': {'o': 1, 'āESCā': 1}, 'nc': {'o': 1, 'āESCā': 1},
         'c': {'o': 3, 'āESCā': 5, 't': 1, ' ': 1, 'u': 1, 'a': 2}, 'Enco': {'d': 1, 'āESCā': 1},
         'nco': {'d': 1, 'āESCā': 1}, 'co': {'d': 1, 'āESCā': 3, 'm': 1, 'n': 1},
         'o': {'d': 1, 'āESCā': 7, 'r': 1, 'f': 1, 's': 1, 'm': 1, 'n': 2, ' ': 1}, 'ncod': {'i': 1, 'āESCā': 1},
         'cod': {'i': 1, 'āESCā': 1}, 'od': {'i': 1, 'āESCā': 1}, 'd': {'i': 1, 'āESCā': 4, 'a': 1, 'e': 2, ' ': 2},
         'codi': {'n': 1, 'āESCā': 1}, 'odi': {'n': 1, 'āESCā': 1}, 'di': {'n': 1, 'āESCā': 1},
         'i': {'n': 2, 'āESCā': 7, 's': 2, 'm': 1, 'v': 2, 'o': 1, 'c': 2, 'd': 2}, 'odin': {'g': 1, 'āESCā': 1},
         'din': {'g': 1, 'āESCā': 1}, 'in': {'g': 1, 'āESCā': 2, 'd': 1}, 'ding': {' ': 1, 'āESCā': 1},
         'ing': {' ': 1, 'āESCā': 1}, 'ing ': {'i': 1, 'āESCā': 1}, 'ng ': {'i': 1, 'āESCā': 1},
         'g ': {'i': 1, 'āESCā': 1}, 'ng i': {'s': 1, 'āESCā': 1}, 'g i': {'s': 1, 'āESCā': 1},
         ' i': {'s': 2, 'āESCā': 2, 'd': 2}, 'g is': {' ': 1, 'āESCā': 1}, ' is': {' ': 2, 'āESCā': 1},
         'is': {' ': 2, 'āESCā': 1}, 's': {' ': 3, 'āESCā': 6, 'i': 3, 's': 3, 'l': 1, 'e': 2, ',': 1},
         ' is ': {'a': 1, 'āESCā': 2, 't': 1}, 'is ': {'a': 1, 'āESCā': 2, 't': 1},
         's ': {'a': 1, 'āESCā': 3, 'd': 1, 't': 1}, 'is a': {' ': 1, 'āESCā': 1}, 's a': {' ': 1, 'āESCā': 1},
         ' a': {' ': 2, 'āESCā': 1}, 'a': {' ': 4, 'āESCā': 4, 't': 1, 's': 1, 'l': 2}, 's a ': {'s': 1, 'āESCā': 1},
         ' a ': {'s': 1, 'āESCā': 2, '“': 1}, 'a ': {'s': 1, 'āESCā': 4, 'c': 1, 'b': 1, '“': 1},
         ' a s': {'i': 1, 'āESCā': 1}, 'a s': {'i': 1, 'āESCā': 1}, ' s': {'i': 1, 'āESCā': 1},
         'a si': {'m': 1, 'āESCā': 1}, ' si': {'m': 1, 'āESCā': 1}, 'si': {'m': 1, 'āESCā': 3, 'o': 1, 'c': 1},
         ' sim': {'p': 1, 'āESCā': 1}, 'sim': {'p': 1, 'āESCā': 1}, 'im': {'p': 1, 'āESCā': 1},
         'm': {'p': 2, 'āESCā': 3, ' ': 1, 'e': 1}, 'simp': {'l': 1, 'āESCā': 1}, 'imp': {'l': 1, 'āESCā': 1},
         'mp': {'l': 1, 'āESCā': 2, 'r': 1}, 'p': {'l': 1, 'āESCā': 2, 'r': 2}, 'impl': {'e': 1, 'āESCā': 1},
         'mpl': {'e': 1, 'āESCā': 1}, 'pl': {'e': 1, 'āESCā': 1}, 'mple': {' ': 1, 'āESCā': 1},
         'ple': {' ': 1, 'āESCā': 1}, 'ple ': {'y': 1, 'āESCā': 1}, 'le ': {'y': 1, 'āESCā': 1},
         'e ': {'y': 1, 'āESCā': 4, 'f': 1, 'b': 1, 'i': 1}, 'le y': {'e': 1, 'āESCā': 1}, 'e y': {'e': 1, 'āESCā': 1},
         ' y': {'e': 1, 'āESCā': 1}, 'y': {'e': 1, 'āESCā': 1}, 'e ye': {'t': 1, 'āESCā': 1},
         ' ye': {'t': 1, 'āESCā': 1}, 'ye': {'t': 1, 'āESCā': 1}, ' yet': {' ': 1, 'āESCā': 1},
         'yet': {' ': 1, 'āESCā': 1}, 'et': {' ': 1, 'āESCā': 1}, 'yet ': {'e': 1, 'āESCā': 1},
         'et ': {'e': 1, 'āESCā': 1}, 't ': {'e': 1, 'āESCā': 2, 'c': 1}, 'et e': {'f': 1, 'āESCā': 1},
         't e': {'f': 1, 'āESCā': 1}, ' e': {'f': 1, 'āESCā': 2, 'l': 1}, 't ef': {'f': 1, 'āESCā': 1},
         ' ef': {'f': 1, 'āESCā': 1}, 'ef': {'f': 1, 'āESCā': 1}, 'f': {'f': 1, 'āESCā': 4, 'e': 1, 'o': 1, ' ': 1},
         ' eff': {'e': 1, 'āESCā': 1}, 'eff': {'e': 1, 'āESCā': 1}, 'ff': {'e': 1, 'āESCā': 1},
         'effe': {'c': 1, 'āESCā': 1}, 'ffe': {'c': 1, 'āESCā': 1}, 'fe': {'c': 1, 'āESCā': 1},
         'ffec': {'t': 1, 'āESCā': 1}, 'fec': {'t': 1, 'āESCā': 1}, 'ec': {'t': 1, 'āESCā': 2, 'u': 1},
         'fect': {'i': 1, 'āESCā': 1}, 'ect': {'i': 1, 'āESCā': 1}, 'ct': {'i': 1, 'āESCā': 1},
         'ecti': {'v': 1, 'āESCā': 1}, 'cti': {'v': 1, 'āESCā': 1}, 'ti': {'v': 2, 'āESCā': 2, 'c': 1},
         'ctiv': {'e': 1, 'āESCā': 1}, 'tiv': {'e': 2, 'āESCā': 1}, 'iv': {'e': 2, 'āESCā': 1},
         'v': {'e': 2, 'āESCā': 1}, 'tive': {' ': 2, 'āESCā': 1}, 'ive': {' ': 2, 'āESCā': 1},
         've': {' ': 2, 'āESCā': 1}, 'ive ': {'f': 1, 'āESCā': 2, 'i': 1}, 've ': {'f': 1, 'āESCā': 2, 'i': 1},
         've f': {'o': 1, 'āESCā': 1}, 'e f': {'o': 1, 'āESCā': 1}, ' f': {'o': 1, 'āESCā': 1},
         'e fo': {'r': 1, 'āESCā': 1}, ' fo': {'r': 1, 'āESCā': 1}, 'fo': {'r': 1, 'āESCā': 1},
         ' for': {'m': 1, 'āESCā': 1}, 'for': {'m': 1, 'āESCā': 1}, 'or': {'m': 1, 'āESCā': 1},
         'r': {'m': 1, 'āESCā': 3, 'e': 3, 'u': 1}, 'form': {' ': 1, 'āESCā': 1}, 'orm': {' ': 1, 'āESCā': 1},
         'rm': {' ': 1, 'āESCā': 1}, 'orm ': {'o': 1, 'āESCā': 1}, 'rm ': {'o': 1, 'āESCā': 1},
         'm ': {'o': 1, 'āESCā': 1}, 'rm o': {'f': 1, 'āESCā': 1}, 'm o': {'f': 1, 'āESCā': 1},
         ' o': {'f': 1, 'āESCā': 1}, 'm of': {' ': 1, 'āESCā': 1}, ' of': {' ': 1, 'āESCā': 1},
         'of': {' ': 1, 'āESCā': 1}, ' of ': {'l': 1, 'āESCā': 1}, 'of ': {'l': 1, 'āESCā': 1},
         'f ': {'l': 1, 'āESCā': 1}, 'of l': {'o': 1, 'āESCā': 1}, 'f l': {'o': 1, 'āESCā': 1},
         ' l': {'o': 1, 'āESCā': 1}, 'f lo': {'s': 1, 'āESCā': 1}, ' lo': {'s': 1, 'āESCā': 1},
         'lo': {'s': 1, 'āESCā': 1}, ' los': {'s': 1, 'āESCā': 1}, 'los': {'s': 1, 'āESCā': 1},
         'os': {'s': 1, 'āESCā': 1}, 'loss': {'l': 1, 'āESCā': 1}, 'oss': {'l': 1, 'āESCā': 1},
         'ss': {'l': 1, 'āESCā': 3, ' ': 1, 'i': 1}, 'ossl': {'e': 1, 'āESCā': 1}, 'ssl': {'e': 1, 'āESCā': 1},
         'sl': {'e': 1, 'āESCā': 1}, 'ssle': {'s': 1, 'āESCā': 1}, 'sle': {'s': 1, 'āESCā': 1},
         'sles': {'s': 1, 'āESCā': 1}, 'les': {'s': 1, 'āESCā': 1}, 'es': {'s': 2, 'āESCā': 2, 'e': 1},
         'less': {' ': 1, 'āESCā': 1}, 'ess': {' ': 1, 'āESCā': 2, 'i': 1}, 'ess ': {'d': 1, 'āESCā': 1},
         'ss ': {'d': 1, 'āESCā': 1}, 'ss d': {'a': 1, 'āESCā': 1}, 's d': {'a': 1, 'āESCā': 1},
         ' d': {'a': 1, 'āESCā': 1}, 's da': {'t': 1, 'āESCā': 1}, ' da': {'t': 1, 'āESCā': 1},
         'da': {'t': 1, 'āESCā': 1}, ' dat': {'a': 1, 'āESCā': 1}, 'dat': {'a': 1, 'āESCā': 1},
         'at': {'a': 1, 'āESCā': 1}, 'data': {' ': 1, 'āESCā': 1}, 'ata': {' ': 1, 'āESCā': 1},
         'ta': {' ': 1, 'āESCā': 1}, 'ata ': {'c': 1, 'āESCā': 1}, 'ta ': {'c': 1, 'āESCā': 1},
         'ta c': {'o': 1, 'āESCā': 1}, 'a c': {'o': 1, 'āESCā': 1}, ' c': {'o': 2, 'āESCā': 2, 'a': 1},
         'a co': {'m': 1, 'āESCā': 1}, ' co': {'m': 1, 'āESCā': 2, 'n': 1}, ' com': {'p': 1, 'āESCā': 1},
         'com': {'p': 1, 'āESCā': 1}, 'om': {'p': 1, 'āESCā': 1}, 'comp': {'r': 1, 'āESCā': 1},
         'omp': {'r': 1, 'āESCā': 1}, 'ompr': {'e': 1, 'āESCā': 1}, 'mpr': {'e': 1, 'āESCā': 1},
         'pr': {'e': 2, 'āESCā': 1}, 'mpre': {'s': 1, 'āESCā': 1}, 'pre': {'s': 2, 'āESCā': 1},
         're': {'s': 2, 'āESCā': 2, 'p': 1}, 'pres': {'s': 1, 'āESCā': 2, 'e': 1}, 'res': {'s': 1, 'āESCā': 2, 'e': 1},
         'ress': {'i': 1, 'āESCā': 1}, 'essi': {'o': 1, 'āESCā': 1}, 'ssi': {'o': 1, 'āESCā': 1},
         'ssio': {'n': 1, 'āESCā': 1}, 'sio': {'n': 1, 'āESCā': 1}, 'io': {'n': 1, 'āESCā': 1},
         'sion': {'.': 1, 'āESCā': 1}, 'ion': {'.': 1, 'āESCā': 1}, 'on': {'.': 1, 'āESCā': 2, 's': 1},
         'ion.': {' ': 1, 'āESCā': 1}, 'on.': {' ': 1, 'āESCā': 1}, 'n.': {' ': 1, 'āESCā': 1},
         '.': {' ': 1, 'āESCā': 1}, 'on. ': {'T': 1, 'āESCā': 1}, 'n. ': {'T': 1, 'āESCā': 1},
         '. ': {'T': 1, 'āESCā': 1}, 'n. T': {'h': 1, 'āESCā': 1}, '. T': {'h': 1, 'āESCā': 1},
         ' T': {'h': 1, 'āESCā': 1}, 'T': {'h': 1, 'āESCā': 1}, '. Th': {'e': 1, 'āESCā': 1},
         ' Th': {'e': 1, 'āESCā': 1}, 'Th': {'e': 1, 'āESCā': 1}, ' The': {' ': 1, 'āESCā': 1},
         'The': {' ': 1, 'āESCā': 1}, 'he': {' ': 1, 'āESCā': 1}, 'The ': {'b': 1, 'āESCā': 1},
         'he ': {'b': 1, 'āESCā': 1}, 'he b': {'a': 1, 'āESCā': 1}, 'e b': {'a': 1, 'āESCā': 1},
         ' b': {'a': 1, 'āESCā': 2, 'e': 1}, 'b': {'a': 1, 'āESCā': 2, 'e': 1}, 'e ba': {'s': 1, 'āESCā': 1},
         ' ba': {'s': 1, 'āESCā': 1}, 'ba': {'s': 1, 'āESCā': 1}, ' bas': {'i': 1, 'āESCā': 1},
         'bas': {'i': 1, 'āESCā': 1}, 'as': {'i': 1, 'āESCā': 1}, 'basi': {'c': 1, 'āESCā': 1},
         'asi': {'c': 1, 'āESCā': 1}, 'asic': {' ': 1, 'āESCā': 1}, 'sic': {' ': 1, 'āESCā': 1},
         'ic': {' ': 1, 'āESCā': 2, 'a': 1}, 'sic ': {'i': 1, 'āESCā': 1}, 'ic ': {'i': 1, 'āESCā': 1},
         'c ': {'i': 1, 'āESCā': 1}, 'ic i': {'d': 1, 'āESCā': 1}, 'c i': {'d': 1, 'āESCā': 1},
         'c id': {'e': 1, 'āESCā': 1}, ' id': {'e': 2, 'āESCā': 1}, 'id': {'e': 2, 'āESCā': 1},
         ' ide': {'a': 1, 'āESCā': 2, 'n': 1}, 'ide': {'a': 1, 'āESCā': 2, 'n': 1}, 'de': {'a': 1, 'āESCā': 2, 'n': 1},
         'idea': {' ': 1, 'āESCā': 1}, 'dea': {' ': 1, 'āESCā': 1}, 'ea': {' ': 1, 'āESCā': 1},
         'dea ': {'b': 1, 'āESCā': 1}, 'ea ': {'b': 1, 'āESCā': 1}, 'ea b': {'e': 1, 'āESCā': 1},
         'a b': {'e': 1, 'āESCā': 1}, 'a be': {'h': 1, 'āESCā': 1}, ' be': {'h': 1, 'āESCā': 1},
         'be': {'h': 1, 'āESCā': 1}, ' beh': {'i': 1, 'āESCā': 1}, 'beh': {'i': 1, 'āESCā': 1},
         'eh': {'i': 1, 'āESCā': 1}, 'behi': {'n': 1, 'āESCā': 1}, 'ehi': {'n': 1, 'āESCā': 1},
         'hi': {'n': 1, 'āESCā': 1}, 'ehin': {'d': 1, 'āESCā': 1}, 'hin': {'d': 1, 'āESCā': 1},
         'hind': {' ': 1, 'āESCā': 1}, 'ind': {' ': 1, 'āESCā': 1}, 'nd': {' ': 1, 'āESCā': 1},
         'ind ': {'R': 1, 'āESCā': 1}, 'nd ': {'R': 1, 'āESCā': 1}, 'd ': {'R': 1, 'āESCā': 2, 'a': 1},
         'nd R': {'L': 1, 'āESCā': 1}, 'd R': {'L': 1, 'āESCā': 1}, ' R': {'L': 1, 'āESCā': 1},
         'd RL': {'E': 1, 'āESCā': 1}, ' RL': {'E': 1, 'āESCā': 1}, 'RL': {'E': 1, 'āESCā': 1},
         'L': {'E': 1, 'āESCā': 1}, ' RLE': {' ': 1, 'āESCā': 1}, 'RLE': {' ': 1, 'āESCā': 1},
         'LE': {' ': 1, 'āESCā': 1}, 'RLE ': {'i': 1, 'āESCā': 1}, 'LE ': {'i': 1, 'āESCā': 1},
         'E ': {'i': 1, 'āESCā': 1}, 'LE i': {'s': 1, 'āESCā': 1}, 'E i': {'s': 1, 'āESCā': 1},
         'E is': {' ': 1, 'āESCā': 1}, 'is t': {'o': 1, 'āESCā': 1}, 's t': {'o': 1, 'āESCā': 1},
         ' t': {'o': 1, 'āESCā': 1}, 's to': {' ': 1, 'āESCā': 1}, ' to': {' ': 1, 'āESCā': 1},
         'to': {' ': 1, 'āESCā': 1}, ' to ': {'r': 1, 'āESCā': 1}, 'to ': {'r': 1, 'āESCā': 1},
         'o ': {'r': 1, 'āESCā': 1}, 'to r': {'e': 1, 'āESCā': 1}, 'o r': {'e': 1, 'āESCā': 1},
         ' r': {'e': 1, 'āESCā': 1}, 'o re': {'p': 1, 'āESCā': 1}, ' re': {'p': 1, 'āESCā': 1},
         ' rep': {'r': 1, 'āESCā': 1}, 'rep': {'r': 1, 'āESCā': 1}, 'ep': {'r': 1, 'āESCā': 1},
         'repr': {'e': 1, 'āESCā': 1}, 'epr': {'e': 1, 'āESCā': 1}, 'epre': {'s': 1, 'āESCā': 1},
         'rese': {'n': 1, 'āESCā': 1}, 'ese': {'n': 1, 'āESCā': 1}, 'se': {'n': 1, 'āESCā': 2, 'c': 1},
         'esen': {'t': 1, 'āESCā': 1}, 'sen': {'t': 1, 'āESCā': 1}, 'sent': {' ': 1, 'āESCā': 1},
         'ent': {' ': 1, 'āESCā': 3, 'i': 1, 's': 1}, 'nt': {' ': 1, 'āESCā': 3, 'i': 1, 's': 1},
         'ent ': {'c': 1, 'āESCā': 1}, 'nt ': {'c': 1, 'āESCā': 1}, 'nt c': {'o': 1, 'āESCā': 1},
         't c': {'o': 1, 'āESCā': 1}, 't co': {'n': 1, 'āESCā': 1}, ' con': {'s': 1, 'āESCā': 1},
         'con': {'s': 1, 'āESCā': 1}, 'cons': {'e': 1, 'āESCā': 1}, 'ons': {'e': 1, 'āESCā': 1},
         'ns': {'e': 1, 'āESCā': 1}, 'onse': {'c': 1, 'āESCā': 1}, 'nse': {'c': 1, 'āESCā': 1},
         'nsec': {'u': 1, 'āESCā': 1}, 'sec': {'u': 1, 'āESCā': 1}, 'secu': {'t': 1, 'āESCā': 1},
         'ecu': {'t': 1, 'āESCā': 1}, 'cu': {'t': 1, 'āESCā': 1}, 'ecut': {'i': 1, 'āESCā': 1},
         'cut': {'i': 1, 'āESCā': 1}, 'ut': {'i': 1, 'āESCā': 1}, 'cuti': {'v': 1, 'āESCā': 1},
         'uti': {'v': 1, 'āESCā': 1}, 'utiv': {'e': 1, 'āESCā': 1}, 've i': {'d': 1, 'āESCā': 1},
         'e i': {'d': 1, 'āESCā': 1}, 'e id': {'e': 1, 'āESCā': 1}, 'iden': {'t': 1, 'āESCā': 1},
         'den': {'t': 1, 'āESCā': 1}, 'dent': {'i': 1, 'āESCā': 1}, 'enti': {'c': 1, 'āESCā': 1},
         'nti': {'c': 1, 'āESCā': 1}, 'ntic': {'a': 1, 'āESCā': 1}, 'tic': {'a': 1, 'āESCā': 1},
         'tica': {'l': 1, 'āESCā': 1}, 'ica': {'l': 1, 'āESCā': 1}, 'ca': {'l': 2, 'āESCā': 1},
         'ical': {' ': 1, 'āESCā': 1}, 'cal': {' ': 1, 'āESCā': 2, 'l': 1}, 'al': {' ': 1, 'āESCā': 2, 'l': 1},
         'cal ': {'e': 1, 'āESCā': 1}, 'al ': {'e': 1, 'āESCā': 1}, 'l ': {'e': 1, 'āESCā': 1},
         'al e': {'l': 1, 'āESCā': 1}, 'l e': {'l': 1, 'āESCā': 1}, 'l el': {'e': 1, 'āESCā': 1},
         ' el': {'e': 1, 'āESCā': 1}, 'el': {'e': 1, 'āESCā': 1}, ' ele': {'m': 1, 'āESCā': 1},
         'ele': {'m': 1, 'āESCā': 1}, 'elem': {'e': 1, 'āESCā': 1}, 'lem': {'e': 1, 'āESCā': 1},
         'em': {'e': 1, 'āESCā': 1}, 'leme': {'n': 1, 'āESCā': 1}, 'eme': {'n': 1, 'āESCā': 1},
         'me': {'n': 1, 'āESCā': 1}, 'emen': {'t': 1, 'āESCā': 1}, 'men': {'t': 1, 'āESCā': 1},
         'ment': {'s': 1, 'āESCā': 1}, 'ents': {',': 1, 'āESCā': 1}, 'nts': {',': 1, 'āESCā': 1},
         'ts': {',': 1, 'āESCā': 1}, 'nts,': {' ': 1, 'āESCā': 1}, 'ts,': {' ': 1, 'āESCā': 1},
         's,': {' ': 1, 'āESCā': 1}, ',': {' ': 1, 'āESCā': 1}, 'ts, ': {'c': 1, 'āESCā': 1},
         's, ': {'c': 1, 'āESCā': 1}, ', ': {'c': 1, 'āESCā': 1}, 's, c': {'a': 1, 'āESCā': 1},
         ', c': {'a': 1, 'āESCā': 1}, ', ca': {'l': 1, 'āESCā': 1}, ' ca': {'l': 1, 'āESCā': 1},
         ' cal': {'l': 1, 'āESCā': 1}, 'call': {'e': 1, 'āESCā': 1}, 'all': {'e': 1, 'āESCā': 1},
         'll': {'e': 1, 'āESCā': 1}, 'alle': {'d': 1, 'āESCā': 1}, 'lle': {'d': 1, 'āESCā': 1},
         'lled': {' ': 1, 'āESCā': 1}, 'led': {' ': 1, 'āESCā': 1}, 'ed': {' ': 1, 'āESCā': 1},
         'led ': {'a': 1, 'āESCā': 1}, 'ed ': {'a': 1, 'āESCā': 1}, 'ed a': {' ': 1, 'āESCā': 1},
         'd a': {' ': 1, 'āESCā': 1}, 'd a ': {'“': 1, 'āESCā': 1}, ' a “': {'r': 1, 'āESCā': 1},
         'a “': {'r': 1, 'āESCā': 1}, ' “': {'r': 1, 'āESCā': 1}, '“': {'r': 1, 'āESCā': 1},
         'a “r': {'u': 1, 'āESCā': 1}, ' “r': {'u': 1, 'āESCā': 1}, '“r': {'u': 1, 'āESCā': 1},
         ' “ru': {'n': 1, 'āESCā': 1}, '“ru': {'n': 1, 'āESCā': 1}, 'ru': {'n': 1, 'āESCā': 1}}

    print(a == b)
